repos:
  - repo: local
    hooks:
      # Run the ruff linter and formatter using just command
      - id: ruff
        name: ruff
        description: "Format Python code using ruff format via just command"
        entry: just format
        language: system
        types_or: [python, pyi]
        pass_filenames: false
        stages: [pre-commit]

  # Mandatory internal hooks
  - repo: https://github.com/uktrade/github-standards
    rev: v1.3.0 # update periodically with pre-commit autoupdate
    hooks:
      - id: run-security-scan
        verbose: false
      - id: run-personal-data-scan
        verbose: false
      - id: validate-security-scan
        verbose: false
