[project]
name = "tangler"
dynamic = ["version"]
description = "Generate testable dirty data for entity resolution."
readme = "README.md"
authors = [{ name="Department for Business and Trade" }]
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "faker>=36.1.1",
    "pandas>=2.3.3",
    "polars>=1.32.3",
    "pyarrow>=17.0.0",
    "pydantic>=2.9.2",
]

[project.urls]
"Documentation" = "https://github.com/uktrade/tangler"
"Repository" = "https://github.com/uktrade/tangler.git"

[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.uv]
default-groups = ["dev"]
package = true
upgrade-package = ["ruff"]

[tool.ruff]
exclude = [
    "*.ipynb"
]
line-length = 88
indent-width = 4
target-version = "py311"
src = ["src"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "D",
    "UP",
    "TID",
    "BLE",
    "PLC",
    "SIM",
    "ANN",
]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.per-file-ignores]
"**/{test,docs}/*" = ["D"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["."]
